version: "3"

services:
  app:
    build: .
    volumes:
      - ./badger:/tmp/badger
    ports:
      - "20000:16000"
    environment:
      - DB_URL=mongodb+srv://tuannguyensn2001a:Zb5m2vXTIvxICiKP@noteme.xjwqdgb.mongodb.net/?retryWrites=true&w=majority
      - GIN_MODE=release